# Generated by Django 2.0.3 on 2018-03-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255, unique=True)),
                ('position', models.CharField(max_length=255, unique=True)),
                ('dates', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MainInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('birthday', models.CharField(max_length=255, unique=True)),
                ('adress', models.CharField(max_length=255, unique=True)),
                ('phonenum', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProyectsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyectname', models.CharField(max_length=255, unique=True)),
                ('positionproy', models.CharField(max_length=255, unique=True)),
                ('descriptionproy', models.CharField(max_length=255, unique=True)),
                ('techinvolved', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkillsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology', models.CharField(max_length=255, unique=True)),
                ('timeskill', models.CharField(max_length=100)),
            ],
        ),
    ]
