# Generated by Django 2.0.3 on 2018-03-12 16:55

from django.db import migrations

def create_initial_info(apps, schema_editor):
    MainInfo = apps.get_model('api', 'MainInfo')
    ExperienceInfo = apps.get_model('api', 'ExperienceInfo')
    SkillsInfo = apps.get_model('api', 'SkillsInfo')
    ProyectsInfo = apps.get_model('api', 'ProyectsInfo')

    MainInfo(name='Armando Canto Garcia', birthday='November 18 1995', adress='avenida 15 de mayo 149', phonenum='2222999727').save()
    ExperienceInfo(company = 'basilio vadillo',position='Martial arts teacher', dates='June-july 2016,2017', description='Basic martial and physical education').save()
    ExperienceInfo(company = 'Uber',position='uber driver', dates='February-june 2016', description='Uber partner as driver').save()
    ExperienceInfo(company = 'None',position='Freelancer', dates='July 2016- present', description='Freelancer developing simple web pages').save()
    ExperienceInfo(company = 'Sal De Gusano',position='Drummer', dates='August 2016-present', description='Drummer in a music band').save()
    SkillsInfo(technology = 'Java',timeskill='2 years').save()
    SkillsInfo(technology = 'C',timeskill='1 year').save()
    SkillsInfo(technology = 'HTML',timeskill='1 year').save()
    SkillsInfo(technology = 'CSS',timeskill='6 months').save()
    SkillsInfo(technology = 'Python',timeskill='3 months').save()
    SkillsInfo(technology = 'PHP',timeskill='1 year').save()
    ProyectsInfo(proyectname = 'RescueMe',positionproy='Web and app developer', descriptionproy= 'App made to provide help in case of a natural disaster',techinvolved = 'HTML,PHP,app inventor').save()
    ProyectsInfo(proyectname = 'Chedraui Textil',positionproy='Front-End Developer', descriptionproy= 'Developed web page for a clothes company',techinvolved = 'HTML,PHP,CSS').save()
    ProyectsInfo(proyectname = 'PatoALV',positionproy='Software Developer', descriptionproy= 'Developed a mario-style game',techinvolved = 'GameMaker').save()



class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
    migrations.RunPython(create_initial_info),    
    ]
