# Generated by Django 2.0.3 on 2018-03-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180312_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentname', models.CharField(max_length=255)),
                ('comment', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='experienceinfo',
            name='company',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='experienceinfo',
            name='dates',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='experienceinfo',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='experienceinfo',
            name='position',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='proyectsinfo',
            name='descriptionproy',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='proyectsinfo',
            name='positionproy',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='proyectsinfo',
            name='proyectname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='proyectsinfo',
            name='techinvolved',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='skillsinfo',
            name='technology',
            field=models.CharField(max_length=255),
        ),
    ]
